package main

import scala.annotation.tailrec

object Problem2 extends App {
//  Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//  By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
  val max = 4000000

  @tailrec
  def sumEvenFibonacci(n1: Int, n2: Int, acc: Int = 0): Int = {
    val total = n1 + n2
    if (total >= max) acc
    else sumEvenFibonacci (n2, total, if(total % 2 == 0) acc + total else acc)
  }
  val answer = sumEvenFibonacci(0, 1)

  println(answer)
}
